import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:hexcolor/hexcolor.dart';

import '../../../doctor_details/view model/doctor_details_cubit.dart';
import '../../../doctor_details/views/doctor details view.dart';
// Import the DoctorDetailsView
import '../../view_model/cubit/cubit.dart';
import '../../view_model/cubit/states.dart';

class ViewAllScreen extends StatelessWidget {
  ViewAllScreen({Key? key, required this.id}) : super(key: key);
  int? id;

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<HomeCubit, HomeStates>(
      listener: (context, state) {},
      builder: (context, state) {
        var cubit = HomeCubit.get(context);
        print(cubit.autogenerated?.data?[id! - 1].doctors?.length ?? 0);
        return Scaffold(
          appBar: AppBar(
            title: Text('View All Doctors'),
            backgroundColor: HexColor('#174068'),
          ),
          body: GridView.builder(
            gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
              crossAxisCount: 2,
              childAspectRatio: 0.7,
              crossAxisSpacing: 16.0,
              mainAxisSpacing: 16.0,
            ),
            itemCount: cubit.autogenerated?.data?[id! - 1].doctors?.length ?? 0,
            itemBuilder: (context, index) {
              final sectionData = cubit.autogenerated?.data?[id! - 1];
              final doctor = sectionData?.doctors![index];

              return DoctorCard(
                doctorName: doctor!.name!,
                specialty: doctor.degree!,
                description: doctor.description!,
                imageUrl: doctor.photo!,
                doctorId: doctor.id!, // Pass the doctor id to the DoctorCard
              );
            },
          ),
        );
      },
    );
  }
}

class DoctorCard extends StatelessWidget {
  final String doctorName;
  final String specialty;
  final String description;
  final String imageUrl;
  final int doctorId; // Add doctorId

  DoctorCard({
    required this.doctorName,
    required this.specialty,
    required this.description,
    required this.imageUrl,
    required this.doctorId, // Add doctorId to the constructor
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 4.0,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(10.0),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            child: Container(
              decoration: BoxDecoration(
                borderRadius: BorderRadius.vertical(top: Radius.circular(10.0)),
                image: DecorationImage(
                  image: NetworkImage(imageUrl),
                  fit: BoxFit.cover,
                ),
              ),
            ),
          ),
          SizedBox(height: 8.0),
          Padding(
            padding: EdgeInsets.symmetric(horizontal: 8.0),
            child: Text(
              doctorName,
              style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
              maxLines: 1, // Set maxLines to 1
              overflow: TextOverflow.ellipsis, // Add ellipsis for overflow
            ),
          ),

          Padding(
            padding: EdgeInsets.symmetric(horizontal: 8.0),
            child: Text(
              specialty,
              style: TextStyle(fontSize: 16, color: Colors.grey),
            ),
          ),
          SizedBox(height: 8.0),
          Padding(
            padding: EdgeInsets.symmetric(horizontal: 8.0),
            child: Text(
              description,
              style: TextStyle(fontSize: 14),
              overflow: TextOverflow.ellipsis,
              maxLines: 2,
            ),
          ),
          SizedBox(height: 8.0),
          Padding(
            padding: EdgeInsets.symmetric(horizontal: 8.0),
            child: ElevatedButton(
              onPressed: () {
                print(doctorId);

                BlocProvider.of<DoctorDetailsCubit>(context).showDetails(doctorId);
                Navigator.of(context).push(
                  MaterialPageRoute(
                    builder: (context) => DoctorDetailsView(id: doctorId),
                  ),
                );
              },
              style: ButtonStyle(
                backgroundColor: MaterialStateProperty.all<Color>(HexColor('#174068')),
                overlayColor: MaterialStateProperty.all<Color>(HexColor('#0D2D4E')),
                shape: MaterialStateProperty.all<RoundedRectangleBorder>(
                  RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(20.0),
                    side: BorderSide(color: Colors.white, width: 2.0),
                  ),
                ),
              ),
              child: Container(
                width: 130.0,
                height: 50.0,
                alignment: Alignment.center,
                decoration: BoxDecoration(
                  gradient: LinearGradient(
                    colors: [
                      HexColor('#174068'),
                      HexColor('#0D2D4E'),
                    ],
                    begin: Alignment.topCenter,
                    end: Alignment.bottomCenter,
                  ),
                  borderRadius: BorderRadius.circular(20.0),
                ),
                child: Text(
                  'Details',
                  textAlign: TextAlign.center,
                  style: TextStyle(color: Colors.white),
                ),
              ),
            ),
          ),
          SizedBox(height: 8.0),
        ],
      ),
    );
  }
}
