import 'package:bloc/bloc.dart';
import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:v_care_clinic/screens/home_screen/view_model/cubit/states.dart';
import 'package:v_care_clinic/screens/register_screen/view_model/cubit/states.dart';

import '../../../../core/cache_helper.dart';
import '../../../../core/dio_helper.dart';
import '../../model/home_model.dart';
import '../../view/widget/home_screen_body.dart';



class HomeCubit extends Cubit<HomeStates> {
  HomeCubit() : super(HomeInitialState());
  static HomeCubit get(context) => BlocProvider.of<HomeCubit>(context);

  final Dio dio = Dio();


  // void addRegister(){
  //   emit(HomeLoadingState());
  //    DioHelper.getData(
  //     url: "/home/index",
  //     token: CacheHelper.getData(key: 'token')
  //   ).then((value) {
  //    print(value);
  //     emit(HomeSuccessState());
  //   }).catchError((errror){
  //     if(errror is DioException){
  //       print(errror.response);
  //     }
  //     print(errror);
  //     if(errror is DioError && errror.response?.statusCode==422){
  //       final e = errror.response?.data;
  //       final m = e["message"];
  //       print(e);
  //       print(m);
  //     }
  //     emit(HomeErrorState());
  //   });

 // }
  Autogenerated? autogenerated;
  Future<void>getAllDoctor()async
  {
    emit(HomeLoadingState());


    try {
      Response  data=await  DioHelper.getData(
          url: 'specialization/index',
          token: CacheHelper.getData(key: "token"));
      if(data.statusCode==200){

        autogenerated=Autogenerated.fromJson(data.data);
      }


      emit(HomeSuccessState());
    } on Exception catch (e)
    {
      if(e is DioError && e.response?.statusCode==401){
        final error = e.response?.data;
        final m = error["message"];
        print(error);
        print(m);
      }
      emit(HomeErrorState());
      print(e.toString());

    }


  }




}
